#!/bin/bash

if [ $# -eq 1 ]; then
    problemId=${1}.cpp
else
    problemId=$(ls -tr *.cpp | tail -n 1)
fi

echo "Compiling $problemId.."
g++ -std=c++11 -g -o a.out $problemId && time ./a.out < input
